# Generated by Django 4.2.1 on 2023-05-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=255)),
                ('poster_url', models.CharField(max_length=255)),
                ('locality_id', models.IntegerField()),
                ('bookable', models.BooleanField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
