# Generated by Django 4.2 on 2023-05-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='bookable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Show Description'),
        ),
        migrations.AlterField(
            model_name='show',
            name='poster_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Show Image'),
        ),
        migrations.AlterField(
            model_name='show',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Show Title'),
        ),
    ]
