# Generated by Django 4.2 on 2023-05-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='types',
            field=models.ManyToManyField(through='reservation.ArtisteType', to='reservation.type'),
        ),
    ]
