# Generated by Django 4.2 on 2023-05-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_artist_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
