# Generated by Django 4.2.1 on 2023-05-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_show_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artistetype',
            table='artist_type',
        ),
    ]
