# Generated by Django 4.2.1 on 2023-05-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_artistetype_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artistetype',
            table=None,
        ),
    ]
