# Generated by Django 4.2 on 2023-05-16 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_artistetype_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artistetype',
            table='artist_type',
        ),
    ]
