# Generated by Django 4.2.1 on 2023-05-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_show_representations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='representations',
        ),
    ]
