# Generated by Django 4.2.1 on 2023-05-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_remove_show_representations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representation',
            name='when',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
