# Generated by Django 4.2.1 on 2023-05-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_alter_representation_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='representations',
            field=models.ManyToManyField(blank=True, to='reservation.representation'),
        ),
    ]
