# Generated by Django 4.2.1 on 2023-05-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_alter_roleuser_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
