# Generated by Django 4.2.1 on 2023-05-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0014_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representationuser',
            name='places',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
