# Generated by Django 4.2.1 on 2023-05-21 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0015_alter_representationuser_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representationuser',
            name='representation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.representation'),
        ),
    ]
