# Generated by Django 4.2.1 on 2023-05-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0017_alter_artist_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='lastname',
            field=models.CharField(max_length=60),
        ),
    ]
