# Generated by Django 4.2.1 on 2023-05-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0018_alter_artist_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='postal_code',
            field=models.IntegerField(max_length=6),
        ),
    ]
